// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// qcbinomC
NumericVector qcbinomC(NumericVector p, NumericVector m, NumericVector g, bool lowertail, bool logp, bool rcb);
RcppExport SEXP _cbinom_qcbinomC(SEXP pSEXP, SEXP mSEXP, SEXP gSEXP, SEXP lowertailSEXP, SEXP logpSEXP, SEXP rcbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< bool >::type lowertail(lowertailSEXP);
    Rcpp::traits::input_parameter< bool >::type logp(logpSEXP);
    Rcpp::traits::input_parameter< bool >::type rcb(rcbSEXP);
    rcpp_result_gen = Rcpp::wrap(qcbinomC(p, m, g, lowertail, logp, rcb));
    return rcpp_result_gen;
END_RCPP
}
// dcblp
NumericMatrix dcblp(NumericVector x, NumericVector m, NumericVector g);
RcppExport SEXP _cbinom_dcblp(SEXP xSEXP, SEXP mSEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(dcblp(x, m, g));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cbinom_qcbinomC", (DL_FUNC) &_cbinom_qcbinomC, 6},
    {"_cbinom_dcblp", (DL_FUNC) &_cbinom_dcblp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_cbinom(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
